[2020-11-09 16:32:18,555: WARNING/MainProcess] /home/manuel/Documentos/git/portafolio/talana_challenge/env/lib/python3.6/site-packages/celery/apps/worker.py:161: CDeprecationWarning: 
Starting from version 3.2 Celery will refuse to accept pickle by default.

The pickle serializer is a security concern as it may give attackers
the ability to execute any command.  It's important to secure
your broker from unauthorized access when using pickle, so we think
that enabling pickle should require a deliberate action and not be
the default choice.

If you depend on pickle then you should set a setting to disable this
warning and to be sure that everything will continue working
when you upgrade to Celery 3.2::

    CELERY_ACCEPT_CONTENT = ['pickle', 'json', 'msgpack', 'yaml']

You must only enable the serializers that you will actually use.


  warnings.warn(CDeprecationWarning(W_PICKLE_DEPRECATED))
[2020-11-09 16:32:20,785: WARNING/MainProcess] /home/manuel/Documentos/git/portafolio/talana_challenge/env/lib/python3.6/site-packages/celery/fixups/django.py:265: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '
[2020-11-09 16:32:20,785: WARNING/MainProcess] celery@manuel-H34 ready.
[2020-11-09 16:36:11,724: WARNING/Worker-5] /home/manuel/Documentos/git/portafolio/talana_challenge/env/lib/python3.6/site-packages/django/template/defaulttags.py:65: UserWarning: A {% csrf_token %} was used in a template, but the context did not provide the value.  This is usually caused by not using RequestContext.
  "A {% csrf_token %} was used in a template, but the context "
[2020-11-09 17:00:13,061: WARNING/Worker-1] /home/manuel/Documentos/git/portafolio/talana_challenge/env/lib/python3.6/site-packages/django/template/defaulttags.py:65: UserWarning: A {% csrf_token %} was used in a template, but the context did not provide the value.  This is usually caused by not using RequestContext.
  "A {% csrf_token %} was used in a template, but the context "
[2020-11-09 22:41:25,171: WARNING/MainProcess] /home/manuel/Documentos/git/portafolio/talana_challenge/env/lib/python3.6/site-packages/celery/apps/worker.py:161: CDeprecationWarning: 
Starting from version 3.2 Celery will refuse to accept pickle by default.

The pickle serializer is a security concern as it may give attackers
the ability to execute any command.  It's important to secure
your broker from unauthorized access when using pickle, so we think
that enabling pickle should require a deliberate action and not be
the default choice.

If you depend on pickle then you should set a setting to disable this
warning and to be sure that everything will continue working
when you upgrade to Celery 3.2::

    CELERY_ACCEPT_CONTENT = ['pickle', 'json', 'msgpack', 'yaml']

You must only enable the serializers that you will actually use.


  warnings.warn(CDeprecationWarning(W_PICKLE_DEPRECATED))
[2020-11-09 22:41:28,667: ERROR/MainProcess] consumer: Cannot connect to amqp://rabbitmquser:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 2.00 seconds...

[2020-11-09 22:41:33,655: ERROR/MainProcess] consumer: Cannot connect to amqp://rabbitmquser:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 4.00 seconds...

[2020-11-09 22:41:40,660: ERROR/MainProcess] consumer: Cannot connect to amqp://rabbitmquser:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 6.00 seconds...

[2020-11-09 22:41:49,660: ERROR/MainProcess] consumer: Cannot connect to amqp://rabbitmquser:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 8.00 seconds...

[2020-11-09 22:42:00,657: ERROR/MainProcess] consumer: Cannot connect to amqp://rabbitmquser:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 10.00 seconds...

[2020-11-09 22:42:13,655: ERROR/MainProcess] consumer: Cannot connect to amqp://rabbitmquser:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 12.00 seconds...

[2020-11-09 22:42:28,669: ERROR/MainProcess] consumer: Cannot connect to amqp://rabbitmquser:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 14.00 seconds...

[2020-11-09 22:42:45,680: ERROR/MainProcess] consumer: Cannot connect to amqp://rabbitmquser:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 16.00 seconds...

[2020-11-09 22:43:04,688: ERROR/MainProcess] consumer: Cannot connect to amqp://rabbitmquser:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 18.00 seconds...

[2020-11-09 22:43:25,698: ERROR/MainProcess] consumer: Cannot connect to amqp://rabbitmquser:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 20.00 seconds...

[2020-11-09 22:43:48,711: ERROR/MainProcess] consumer: Cannot connect to amqp://rabbitmquser:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 22.00 seconds...

[2020-11-09 22:44:13,729: ERROR/MainProcess] consumer: Cannot connect to amqp://rabbitmquser:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 24.00 seconds...

[2020-11-09 22:44:40,744: ERROR/MainProcess] consumer: Cannot connect to amqp://rabbitmquser:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 26.00 seconds...

[2020-11-09 22:45:09,765: ERROR/MainProcess] consumer: Cannot connect to amqp://rabbitmquser:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 28.00 seconds...

[2020-11-09 22:45:40,780: ERROR/MainProcess] consumer: Cannot connect to amqp://rabbitmquser:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 30.00 seconds...

[2020-11-09 22:46:13,820: ERROR/MainProcess] consumer: Cannot connect to amqp://rabbitmquser:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

[2020-11-09 22:46:48,842: ERROR/MainProcess] consumer: Cannot connect to amqp://rabbitmquser:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

[2020-11-09 22:47:23,873: ERROR/MainProcess] consumer: Cannot connect to amqp://rabbitmquser:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

[2020-11-09 22:47:58,901: ERROR/MainProcess] consumer: Cannot connect to amqp://rabbitmquser:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

[2020-11-09 22:48:33,924: ERROR/MainProcess] consumer: Cannot connect to amqp://rabbitmquser:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

[2020-11-09 22:49:08,948: ERROR/MainProcess] consumer: Cannot connect to amqp://rabbitmquser:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

[2020-11-09 22:49:43,973: ERROR/MainProcess] consumer: Cannot connect to amqp://rabbitmquser:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

[2020-11-09 22:50:19,005: ERROR/MainProcess] consumer: Cannot connect to amqp://rabbitmquser:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

[2020-11-09 22:50:54,033: ERROR/MainProcess] consumer: Cannot connect to amqp://rabbitmquser:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

[2020-11-09 22:51:29,057: ERROR/MainProcess] consumer: Cannot connect to amqp://rabbitmquser:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 32.00 seconds...

